export let data = [
    //! ============================ Single rooms =====================
    {
        title: "single",
        price: 60,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/03/28/09/34/bedroom-1285156_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:1
    },
    {
        title: "single",
        price: 50,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2020/10/18/09/16/bedroom-5664221_960_720.jpg",
        kids: "",
        adults:"",
        info: "breakfast",
        rate:3,
        id:2
    },
    {
        title: "single",
        price: 55,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2019/08/19/13/58/bed-4416515_960_720.jpg",
        kids: "",
        adults:"",
        info: "breakfast",
        rate:3,
        id:3
    },
    {
        title: "single",
        price: 70,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2018/06/14/21/15/bedroom-3475656_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:4,
        id:4
    },
    {
        title: "single",
        price: 90,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2014/10/16/08/39/bedroom-490779_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:5,
        id:5
    },
    //! ============================= Double rooms ===================
    {
        title: "double",
        price: 120,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/06/10/01/05/hotel-room-1447201_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:6
    },
    {
        title: "double",
        price: 130,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:7
    },
    {
        title: "double",
        price: 135,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/04/15/11/46/hotel-1330846_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:8
    },
    {
        title: "double",
        price: 160,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/11/14/02/28/apartment-1822409_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:4,
        id:9
    },
    {
        title: "double",
        price: 200,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/07/08/23/36/beach-house-1505461_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:5,
        id:10
    },
    //! ===================== Triple ==============
    {
        title: "triple",
        price: 150,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2017/04/28/22/16/room-2269594_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:11
    },
    {
        title: "triple",
        price: 160,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/09/18/03/28/travel-1677347_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:12
    },
    {
        title: "triple",
        price: 160,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2020/01/15/18/02/room-4768553_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:13
    },
    {
        title: "triple",
        price: 220,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/11/14/02/29/apartment-1822410_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:4,
        id:14
    },
    {
        title: "triple",
        price: 260,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2014/05/21/14/56/bedroom-349698_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:5,
        id:15
    },
    //! ======================= Quad ======================
    {
        title: "quad",
        price: 200,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2015/01/10/11/39/hotel-595121_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:16
    },
    {
        title: "quad",
        price: 220,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2015/01/16/08/54/motel-601218_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:17
    },
    {
        title: "quad",
        price: 250,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/04/15/11/45/hotel-1330841_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:18
    },
    {
        title: "quad",
        price: 290,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2020/01/15/18/01/room-4768551_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:4,
        id:19
    },
    {
        title: "quad",
        price: 330,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2020/02/01/06/12/living-room-4809587_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:5,
        id:20
    },
    //! ========================= Queen ==================
    {
        title: "queen",
        price: 300,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2015/01/16/11/19/hotel-601327_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:21
    },
    {
        title: "queen",
        price: 350,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2014/09/26/19/45/bedroom-462772_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:3,
        id:22
    },
    {
        title: "queen",
        price: 400,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/04/15/11/43/hotel-1330834_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:4,
        id:23
    },
    {
        title: "queen",
        price: 420,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/07/08/23/33/hotel-room-1505455_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:5,
        id:24
    },
    {
        title: "queen",
        price: 450,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2014/09/25/18/05/bedroom-460762_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast",
        rate:5,
        id:25
    },
    //! =========================== King ==========================

 {
        title: "king",
        price: 400,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2017/08/10/07/32/hotel-room-2619509_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast swimming-pool dinner",
        rate:4,
        id:26
    },
    {
        title: "king",
        price: 420,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2016/04/15/11/48/hotel-1330847_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast swimming-pool dinner",
        rate:4,
        id:27
    },
    {
        title: "king",
        price: 450,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2014/05/21/14/56/bedroom-349699_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast swimming-pool dinner",
        rate:5,
        id:28
    },
    {
        title: "king",
        price: 470,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2021/10/06/15/05/bedroom-6686061_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast swimming-pool dinner",
        rate:5,
        id:29
    },
    {
        title: "king",
        price: 500,
        startDate: "",
        endDate: "",
        img: "https://cdn.pixabay.com/photo/2019/06/02/12/27/apartment-4246371_960_720.jpg",
        kids: "",
        adults:"",
        info: "wifi breakfast swimming-pool dinner",
        rate:5,
        id:30
    },

]